### ISSUE TITLE
【问卷调查】你希望如何使用本repo？

### ISSUE THREAD

**Issue by robturtle** [leetcode-study-group/leetcode-solutions#1]
关于公共repo：我的想法就是，能把大家做题过程中非常有帮助的 文献，自己做的有用的笔记总结，以及最佳实践代码 都陆续汇总进来。所以关于repo的收集方面，我想做个调查：大家比较倾向于哪种使用方式？

1. 每个人都fork一个empty分支，在觉得主分支需要增补替换的时候pull request
2. 每个人都有主分支的写权限，随意增补，在与原提交者交流后自由替换原内容

如果倾向于1，请回复1；倾向于2，请回复2。

P.S.

- 有关本repo文件格式约定，安装推荐及其他信息，可以在[README](https://github.com/leetcode-study-group/leetcode-java-solutions/blob/master/README.md)里找到。
- 不管是否直接向此repo添加内容，仍然欢迎fork它的[empty](https://github.com/leetcode-study-group/leetcode-java-solutions/tree/empty)分支以作个人笔记用。

另任何有关此repo的建议及问题，均可在楼下留言。

**Comment by zhuwhr** [comment]
2。理由是每个组员都是小组的主人，而且互相之间的交流应该被全组看到并提意见。但是不好处是，如果A对B写的东西提出意见，当做主分支一样写上去供大家选择，这样是不是就得肉眼找不同了？不像pull request一样能马上看出不同来？

**Comment by robturtle** [comment]
2的话，所有冲突处的修改都是要经过事前沟通的，因为大家都认识，所以可以这么搞。

**Comment by zhuwhr** [comment]
好的，听起来很不错，等待更多人的意见

**Comment by zhouyuanquaner** [comment]
同意2，增强互动性，比较容易大家分享&获取知识和心得。
如果有冲突之类的，大家能够及时讨论

**Comment by Brucenyu** [comment]
1 用pull request比较容易找不同吧，然后每次聚会的时候提出来，然后合并？

**Comment by robturtle** [comment]
@Brucenyu PR 这个并不是PR相对于直接编辑的优势。我这么问的原因是，不清楚有多少人更愿意重头创建自己的笔记repo，而不是直接贡献在这里。

目前刷题阶段，我还是把权限改成了全部人都能写。并且现在也把所有语言的repo都建好了。欢迎大家在自己认领自己喜欢的语言repo，直接在上面添加笔记就好。
