### ISSUE TITLE
#53 maxCrossSubarray

### ISSUE THREAD

**Issue by robturtle** [leetcode-study-group/leetcode-solutions#5]
[By Jun Li]
我刚刚在leetcode上碰到了算法课老师讲过的题，leetcode是53题，max subarray，然而按照老师的伪代码写出来答案的有问题，不知道是我上课笔记抄错了还是怎么回事
老师没有考虑动规，所以不对…
主要是这个函数

［函数］

**Comment by lijunray** [comment]
按照老师的伪代码，先求左边的最大值，再求右边的最大值，再求cross mid的最大值，然后比较这三个值取最大，我写的cpp代码如下：
`class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        return help(nums, 0, nums.size() - 1);
    }
    
    int help(vector<int>& nums, int left, int right) {
        if (left == right) {
            return nums[left];
        }
        int mid = (left + right) / 2;
        int leftSum = help(nums, left, mid);
        int rightSum = help(nums, mid + 1, right);
        int crossSum = cross(nums, left, mid, right);
        
        if (leftSum > rightSum && leftSum > crossSum) {
            return leftSum;
        }
        else if (rightSum > leftSum && rightSum > crossSum) {
            return rightSum;
        }
        else if (crossSum > leftSum && crossSum > rightSum) {
            return crossSum;
        }
    } 
    
    int cross(vector<int>& nums, int left, int mid, int right) {
        int leftMax = nums[mid];
        int rightMax = nums[mid + 1];
        
        for (int i = mid - 1; i >= left; i--) {
            if (leftMax + nums[i] >= leftMax) {
                leftMax = leftMax + nums[i];
            }
            else {
                break;
            }
        }
        
        for (int i = mid + 2; i <= right; i++) {
            if (rightMax+nums[i] >= rightMax) {
                rightMax = rightMax + nums[i];
            }
            else {
                break;
            }
        }
        
        return leftMax + rightMax;
    }
    
};`

但是这其中没有考虑dp，所以如果出现比如[1,2,3,4,5,-2,2,10]的情况，遇到-2右边就会停止，认为5就是最大值，实际上是5-2+2+10=15。我觉得大概是我抄笔记抄错了？或者老师要我们自己考虑动规？

**Comment by robturtle** [comment]
先说函数规范的问题

1. help 这个名字不好
2. c 系语言偏好左开右闭的区间，常用词有 begin, end (STL规范), lo, hi, 如果需要用左闭右闭，常用 first, last (STL 规范)
2+. c++ 里面更偏好用iterator
3. help函数corner case有误，试考虑 nums.size() == 0。（左开右闭区间没有这个问题）
4. 跳转流程可以简化

再说逻辑问题
你自己写错了，应该一直累积sum到最后，没有break

```cpp
class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        return maxSubArray(nums, nums.begin(), nums.end());
    }
    
private:
    int maxSubArray(vector<int> &nums, vector<int>::iterator lo, vector<int>::iterator hi) {
        if (lo >= hi) return INT_MIN;
        if (lo + 1 == hi) return *lo;
        auto mid = lo + (hi - lo) / 2;
        int maxLeft  = maxSubArray(nums, lo, mid);
        int maxRight = maxSubArray(nums, mid, hi);
        int maxCross = maxCrossMiddle(nums, lo, mid, hi);
        if (maxRight > maxLeft) {
            return maxRight > maxCross ? maxRight : maxCross;
        } else {
            return maxLeft > maxCross ? maxLeft : maxCross;
        }
    }
    
    int maxCrossMiddle(vector<int> &nums,
                       vector<int>::iterator lo,
                       vector<int>::iterator mid,
                       vector<int>::iterator hi) {
        int sum = 0;
        int leftMax = INT_MIN;
        for (auto it = mid - 1; it >= lo; --it) {
            sum += *it;
            if (sum > leftMax) leftMax = sum;
        }
        
        sum = 0;
        int rightMax = INT_MIN;
        for (auto it = mid; it < hi; ++it) {
            sum += *it;
            if (sum > rightMax) rightMax = sum;
        }
        return leftMax + rightMax;
    }
};
```

**Comment by lijunray** [comment]
懂了，谢谢
